services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-end/.env
  
  vite:
    container_name: vite
    build: ./front-end
    volumes:
      - vite-volume:/var/www/html
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - vite-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - vite

volumes:
  postgres-volume:
  vite-volume: